### ISSUE TITLE
Там были траты по трём категориям

### ISSUE THREAD

**Issue by coursar** [Dinar-92/Bank-service#1]
https://github.com/Dinar-92/Bank-service/blob/cb82909b2515b1b96604df1debbc1b983d50c9f4/src/BankService.java#L6-L9

**Comment by Dinar-92** [comment]
Добавлены траты по категориям
https://github.com/Dinar-92/Bank-service/blob/master/src/BankService.java

**Comment by coursar** [comment]
Issue надо закрывать сообщениями коммита, а не ссылками

**Comment by Dinar-92** [comment]
Добавлены траты по категориям
https://github.com/Dinar-92/Bank-service/blob/173bc52bab8cf333a7972f1cdc1947f42ad71400/src/BankService.java#L1-L18
